### PR TITLE
Add a google analytics dump

### PR DESCRIPTION
**Pull request by choldgraf**
This adds an aggregate dump of google analytics data for mybinder.org. It's from roughly the last 6 months. I'm not sure what's the right level of granularity to make public here (e.g. because you could probably identify people if we included user-level data) so somebody should confirm that this is an OK dataset to share.

### CODE REVIEW

**Comment by yuvipanda** [comment]
This is great! I think even having day granularity is fine, as long as we exclude repos used under a certain limit (5?)

**Comment by choldgraf** [comment]
hmmm, I can try to get that granularity of data...lemme look into it when I have a moment

**Comment by choldgraf** [comment]
I *think* this may actually be better-carried-out by @jzf2101 who I believe is working on a much more fine-grained and data-rich dataset of Binder usage. Correct me if I'm wrong Jessica!

**Comment by jzf2101** [comment]
@choldgraf yes I have something we can share finishing up details !

**Comment by choldgraf** [comment]
sweet! I'm not sure the best place for the code itself, maybe here: https://github.com/jupyterhub/mybinder-tools ?

**Comment by jzf2101** [comment]
Do we want to put them in separate places? I don't know if that makes sense?

**Comment by choldgraf** [comment]
well I was thinking `binder-data` would be "purely" a data repository (until we worked out a better place for data to be stored/distributed). E.g., all the code to analyze the billing data is here: https://github.com/jupyterhub/binder-billing even though the data is stored in this repo.

Alternatively we could have a `scripts/` folder here...I'm kinda 50/50 on it.

**Comment by jzf2101** [comment]
I use my code to get additional gh data so I figured the code would be shared in the same place :/

**Comment by choldgraf** [comment]
that's fine w/ me too - more important that the code is up somewhere rather than it's up in exactly the correct place :-)

**Comment by choldgraf** [comment]
@jzf2101 ping on this, shall I close this issue?

**Review by jzf2101 — APPROVED** [review]
This is a good start I can build off it

**Comment by choldgraf** [comment]
hey @jzf2101 - any movement on this? Just a friendly check-in!

**Comment by jzf2101** [comment]
Been behind on this from the ICML data collection stuff, but I can do this for the binder workshop

**Comment by choldgraf** [comment]
cc @betatim - shall I close this now that you've got #12 open?

**Comment by betatim** [comment]
We could also merge this, then add #12?

**Comment by choldgraf** [comment]
I'm happy to merge this whenever, just been waiting for somebody to press the green button

**Pull request merged**
